###############################################################################
# MinIO Deployment – 1 Replica, with Console exposed properly on port 9090
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: kubeflow-user-example-com
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      # annotations: # With this it does not work
      #  sidecar.istio.io/inject: "false" 
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubeflow-control-plane
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
          - server
          - /data
        env:
        - name: MINIO_ROOT_USER
          value: "minioDev" # DO NOT DO THIS IN PRODUCTION, just for demo purposes
        - name: MINIO_ROOT_PASSWORD
          value: "minioDevPass123" # DO NOT DO THIS IN PRODUCTION, just for demo purposes
        - name: MINIO_SERVER_URL
          value: "http://minio.kubeflow-user-example-com.svc:9000"
        - name: MINIO_CONSOLE_ADDRESS
          value: ":9090"
        ports:
        - name: api
          containerPort: 9000
        - name: console
          containerPort: 9090
        volumeMounts:
        - name: localvolume
          mountPath: /data
      volumes:
      - name: localvolume
        hostPath:
          path: /mnt/disk1/data
          type: DirectoryOrCreate

---
###############################################################################
# Service – exposes 9000 (API) and 9090 (Console)
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: kubeflow-user-example-com
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: api
  - name: console
    port: 9090
    targetPort: console